### ISSUE TITLE
Bool optimisation?

### ISSUE THREAD

**Issue by Vlix** [arnemileswinter/itc#4]
I have taken some time to look through the source code (but not enough to look through EVERYTHING) and it seems to me the `Bool` in the `ITCId` isn't actually used in any boolean sense, more just like a 0 or 1 flag.

So it might be a slight optimization (less allocations) to just rewrite the `ITCId` definition to:
```hs
data ITCId
    = ITCIdBranch ITCId ITCId
    | ITCIdActive
    | ITCIdInactive -- or whatever description makes sense
    deriving (Eq, Show)
```

**Comment by arnemileswinter** [comment]
Thx, I like it!

Paper uses literals 0 or 1 exactly like you described it, so I thought to just use boolean for clarity. Yours is even more clear!
